# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import getsong.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=getsong.models.user_path)),
                ('song_url', models.URLField(max_length=100)),
                ('user_url', models.URLField(max_length=100)),
            ],
        ),
    ]
